version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always